### ISSUE TITLE
Release tags

### ISSUE THREAD

**Issue by brendanf** [RybergGroup/phylommand#4]
Could you tag at least one commit as a release?  Then I can make a Conda recipe for it.

**Comment by mr-y** [comment]
Phylommand is published as:
Ryberg M. Phylommand - a command line software package for phylogenetics [version 1; peer review: 2 approved with reservations]. F1000Research 2016, 5:2903
(https://doi.org/10.12688/f1000research.10446.1)

**Comment by mr-y** [comment]
Release now created.
